version: 0.2

env:
  variables:
    S3_BUCKET: "kkdtest1"    # CHANGE THIS

phases:
  install:
    commands:
      - echo "Install step completed"
  build:
    commands:
      - echo "Build step (run your build commands if needed)"
      # Example: npm commands (optional)
      # - npm install
      # - npm run build
  post_build:
    commands:
      - echo "Uploading index.html"
      - aws s3 cp ./index.html s3://kkdtest1/index.html --content-type "text/html"

artifacts:
  files:
    - '**/*'
