version: 0.2

phases:
  install:
    commands:
      - echo "Install phase started"
      - python --version
  build:
    commands:
      - echo "Build phase started"
      - echo "Running Hello World program..."
      - python hello.py

artifacts:
  files:
    - '**/*'
